### ISSUE TITLE
Error when generating template from controller

### ISSUE THREAD

**Issue by simonjnesta** [mwnciau/rblade-intellij#9]
```
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action only (see Application.runReadAction()); see https://jb.gg/ij-platform-threading for details
Current thread: Thread[#1308,DefaultDispatcher-worker-7,6,main] 1882714136 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[#54,AWT-EventQueue-0,6,main] 1956833436
	at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:177)
	at com.intellij.util.concurrency.ThreadingAssertions.softAssertReadAccess(ThreadingAssertions.java:129)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:162)
	at org.jetbrains.vuejs.lang.VueScriptLangs.getLatestKnownLang(VueScriptLangs.kt:65)
	at org.jetbrains.vuejs.lang.html.highlighting.VueSyntaxHighlighterFactory.getSyntaxHighlighter(VueSyntaxHighlighterFactory.kt:17)
	at com.intellij.openapi.fileTypes.SyntaxHighlighterFactory.getSyntaxHighlighter(SyntaxHighlighterFactory.java:38)
	at com.mwnciau.rblade.highlighter.RBladeEditorHighlighter.updateLayers(RBladeEditorHighlighter.kt:38)
	at com.intellij.openapi.editor.ex.util.LayeredLexerEditorHighlighter.setText(LayeredLexerEditorHighlighter.java:119)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider$createFileEditor$2$highlighterDeferred$1.invokeSuspend(PsiAwareTextEditorProvider.kt:73)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
```

```
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action only (see Application.runReadAction()); see https://jb.gg/ij-platform-threading for details
Current thread: Thread[#1308,DefaultDispatcher-worker-7,6,main] 1882714136 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[#54,AWT-EventQueue-0,6,main] 1956833436
	at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:177)
	at com.intellij.util.concurrency.ThreadingAssertions.softAssertReadAccess(ThreadingAssertions.java:129)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findFile(FileManagerImpl.java:373)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:163)
	at org.jetbrains.vuejs.lang.VueScriptLangs.getLatestKnownLang(VueScriptLangs.kt:65)
	at org.jetbrains.vuejs.lang.html.highlighting.VueSyntaxHighlighterFactory.getSyntaxHighlighter(VueSyntaxHighlighterFactory.kt:17)
	at com.intellij.openapi.fileTypes.SyntaxHighlighterFactory.getSyntaxHighlighter(SyntaxHighlighterFactory.java:38)
	at com.mwnciau.rblade.highlighter.RBladeEditorHighlighter.updateLayers(RBladeEditorHighlighter.kt:38)
	at com.intellij.openapi.editor.ex.util.LayeredLexerEditorHighlighter.setText(LayeredLexerEditorHighlighter.java:119)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider$createFileEditor$2$highlighterDeferred$1.invokeSuspend(PsiAwareTextEditorProvider.kt:73)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
```

**Comment by simonjnesta** [comment]
Updated error:

com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action only (see Application.runReadAction()); If you access or modify model on EDT consider wrapping your code in WriteIntentReadAction  or ReadAction; see https://jb.gg/ij-platform-threading for details
Current thread: Thread[#21,DefaultDispatcher-worker-4,5,main] 1147535868 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[#61,AWT-EventQueue-0,6,main] 1120260942
	at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:257)
	at com.intellij.util.concurrency.ThreadingAssertions.softAssertReadAccess(ThreadingAssertions.java:173)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:160)
	at org.jetbrains.vuejs.lang.VueScriptLangs.getLatestKnownLang(VueScriptLangs.kt:65)
	at org.jetbrains.vuejs.lang.html.highlighting.VueSyntaxHighlighterFactory.getSyntaxHighlighter(VueSyntaxHighlighterFactory.kt:17)
	at com.intellij.openapi.fileTypes.SyntaxHighlighterFactory.getSyntaxHighlighter(SyntaxHighlighterFactory.java:38)
	at com.mwnciau.rblade.highlighter.RBladeEditorHighlighter.updateLayers(RBladeEditorHighlighter.kt:38)
	at com.intellij.openapi.editor.ex.util.LayeredLexerEditorHighlighter.setText(LayeredLexerEditorHighlighter.java:119)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider$createFileEditor$2$highlighterDeferred$1.invokeSuspend(PsiAwareTextEditorProvider.kt:69)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
